# Render fournit le port via la variable d'environnement PORT
server.port=${PORT:8080}

# PostgreSQL (Render)
spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

# Schema: en prod on ne drop pas la base à chaque redémarrage
spring.jpa.hibernate.ddl-auto=update
spring.jpa.defer-datasource-initialization=true

# Charger data.sql (si tu veux garder tes données de base en prod)
spring.sql.init.mode=never
spring.sql.init.encoding=UTF-8

# Base path REST identique à dev
spring.data.rest.base-path=api

# Logs (plus silencieux en prod)
logging.level.org.hibernate.SQL=INFO
logging.level.web=INFO

# Gmail SMTP (Spring Mail)
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=${SPRING_MAIL_USERNAME}
spring.mail.password=${SPRING_MAIL_PASSWORD}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

app.mail.from=${proog4420@gmail.com}


# SendGrid 
app.mail.from=${MAIL_FROM}
app.sendgrid.api-key=${SENDGRID_API_KEY}